name: fenicsx-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fenics-dolfinx >=0.10.0
  - mpi4py
  - petsc
  - petsc4py
  - ufl
  - basix
  - ffcx
  - pyvista
  - matplotlib
  - jupyterlab
